NOKIA_RECORD_TYPE_MAPPING = {
    # Mapeamento de tipos de registros de CDR Nokia do teleparser para seus códigos correspondentes.
    "Call to a roaming subscriber": "ROAM",
    "Camel-originated call": "COC",
    "Camel-terminated call": "CTC",
    "Device-originated call": "DOC",
    "Forwarded call": "FORW",
    "HLR interrogation": "HLRI",
    "Header": "HEA",
    "IN-forwarded short message service": "SMMF",
    "Intelligent network data 1": "IN1",
    "Intelligent network data 2": "IN2",
    "Intelligent network data 3": "IN3",
    "Intelligent network data 4": "IN4",
    "Intelligent network data 5": "IN5",
    "Location service": "LCS",
    "Location update": "LOCA",
    "Mobile-originated call": "MOC",
    "Mobile-terminated call": "MTC",
    "PBX-originated call": "PBXO",
    "PBX-terminated call": "PBXT",
    "PSTN-originated call": "POC",
    "PSTN-terminated call": "PTC",
    "Remote charging control": "RCC",
    "Short message service (point-to-point), mobile-originated": "SMMO",
    "Short message service (point-to-point), mobile-terminated": "SMMT",
    "SIP CDR for registration": "SIPR",
    "SIP-originated call": "SOC",
    "SIP-originating message": "SOM",
    "SIP-terminated call": "STC",
    "SIP-terminating message": "STM",
    "Supplementary service": "SUPS",
    "Trailer record": "TRA",
    "Unstructured supplementary service data": "USSD",
    "Unsuccessful call attempt": "UCA",
    "Use of hardware": "HW",
}
