from pyspark.sql.types import StringType, StructField, StructType

stfc_pit_claro_schema = StructType(
    [
        StructField("recordType", StringType(), True),
        StructField("recordingEntity", StringType(), True),
        StructField("mscIncomingROUTE", StringType(), True),
        StructField("mscOutgoingROUTE", StringType(), True),
        StructField("callingNumber ", StringType(), True),
        StructField("calledNumber ", StringType(), True),
        StructField("isdnBasicService ", StringType(), True),
        StructField("seizureTime", StringType(), True),
        StructField("answerTime", StringType(), True),
        StructField("releaseTime", StringType(), True),
        StructField("callDuration", StringType(), True),
        StructField("causeForTerm ", StringType(), True),
        StructField("diagnostics_gsm0408 ", StringType(), True),
        StructField("diagnostics_gsm0902 ", StringType(), True),
        StructField("diagnostics_ccittQ767 ", StringType(), True),
        StructField("callReference", StringType(), True),
        StructField("sequenceNumber", StringType(), True),
        StructField("recordExtensions", StringType(), True),
        StructField("partialRecordType", StringType(), True),
        StructField("basicservice_bearerService ", StringType(), True),
        StructField("basicservice_teleservice ", StringType(), True),
        StructField("basicservice_isdnService ", StringType(), True),
        StructField("additionalChgInfo_chargeIndicat", StringType(), True),
        StructField("additionalChgInfo_chargeParamet", StringType(), True),
        StructField("ussdCallBackFlag", StringType(), True),
        StructField("originalCalledNumber ", StringType(), True),
        StructField("chargeAreaCode ", StringType(), True),
        StructField("rateIndication", StringType(), True),
        StructField("roamingNumber", StringType(), True),
        StructField("mscOutgoingCircuit", StringType(), True),
        StructField("mscIncomingCircuit", StringType(), True),
        StructField("orgMSCId ", StringType(), True),
        StructField("callEmlppPriority ", StringType(), True),
        StructField("eaSubscriberInfo ", StringType(), True),
        StructField("selectedCIC ", StringType(), True),
        StructField("callerportedflag ", StringType(), True),
        StructField("subscriberCategory ", StringType(), True),
        StructField("cUGOutgoingAccessIndicator ", StringType(), True),
        StructField("cUGInterlockCode ", StringType(), True),
        StructField("cUGIncomingAccessUsed", StringType(), True),
        StructField("mscIncomingRouteAttribute ", StringType(), True),
        StructField("mscOutgoingRouteAttribute ", StringType(), True),
        StructField("networkCallReference", StringType(), True),
        StructField("setupTime", StringType(), True),
        StructField("alertingTime", StringType(), True),
        StructField("voiceIndicator", StringType(), True),
        StructField("bCategory ", StringType(), True),
        StructField("callType", StringType(), True),
        StructField("chargePulseNum ", StringType(), True),
        StructField("disconnectparty ", StringType(), True),
        StructField("chargePulseNumforITXTXA ", StringType(), True),
        StructField("networkOperatorId ", StringType(), True),
        StructField("audioDataType", StringType(), True),
        StructField("recordNumber ", StringType(), True),
        StructField("partyRelCause_releaseParty ", StringType(), True),
        StructField("partyRelCause_releaseCause ", StringType(), True),
        StructField("chargeLevel", StringType(), True),
        StructField("locationNum ", StringType(), True),
        StructField("locationNumberNai", StringType(), True),
        StructField("translatedNumber", StringType(), True),
        StructField("cmnFlag ", StringType(), True),
        StructField("icidvalue ", StringType(), True),
        StructField("origioi ", StringType(), True),
        StructField("termioi ", StringType(), True),
        StructField("calledportedflag ", StringType(), True),
        StructField("locationroutingnumber ", StringType(), True),
        StructField("intermediateChargingInd ", StringType(), True),
        StructField("mscOutgoingROUTENumber", StringType(), True),
        StructField("mscIncomingROUTENumber", StringType(), True),
        StructField("drcCallId", StringType(), True),
        StructField("drcCallRN", StringType(), True),
        StructField("nPDipIndicator ", StringType(), True),
        StructField("aNSIRoutingNumber ", StringType(), True),
        StructField("lRNSource ", StringType(), True),
        StructField("wPSCallFlag ", StringType(), True),
        StructField("redirectingNumber ", StringType(), True),
        StructField("redirectingCounter ", StringType(), True),
        StructField("officeName ", StringType(), True),
        StructField("npa-Nxx ", StringType(), True),
        StructField("globalCallReference ", StringType(), True),
        StructField("callerIpInfo_origIpAddress ", StringType(), True),
        StructField("callerIpInfo_termIpAddress ", StringType(), True),
        StructField("callerIpInfo_passertedId ", StringType(), True),
        StructField("callerIpInfo_usedCodec1 ", StringType(), True),
        StructField("callerIpInfo_usedCodec2 ", StringType(), True),
        StructField("callerIpInfo_usedCodec3 ", StringType(), True),
        StructField("callerIpInfo_usedCodec4 ", StringType(), True),
        StructField("callerIpInfo_usedCodec5 ", StringType(), True),
        StructField("callerIpInfo_usedCodec6 ", StringType(), True),
        StructField("callerIpInfo_usedCodec7 ", StringType(), True),
        StructField("callerIpInfo_usedCodec8 ", StringType(), True),
        StructField("callerIpInfo_originatingPort ", StringType(), True),
        StructField("callerIpInfo_terminatingPort ", StringType(), True),
        StructField("callerIpInfo_qosStatistics ", StringType(), True),
        StructField("calledIpInfo_origIpAddress ", StringType(), True),
        StructField("calledIpInfo_termIpAddress ", StringType(), True),
        StructField("calledIpInfo_passertedId ", StringType(), True),
        StructField("calledIpInfo_usedCodec1 ", StringType(), True),
        StructField("calledIpInfo_usedCodec2 ", StringType(), True),
        StructField("calledIpInfo_usedCodec3 ", StringType(), True),
        StructField("calledIpInfo_usedCodec4 ", StringType(), True),
        StructField("calledIpInfo_usedCodec5 ", StringType(), True),
        StructField("calledIpInfo_usedCodec6 ", StringType(), True),
        StructField("calledIpInfo_usedCodec7 ", StringType(), True),
        StructField("calledIpInfo_usedCodec8 ", StringType(), True),
        StructField("calledIpInfo_originatingPort ", StringType(), True),
        StructField("calledIpInfo_terminatingPort ", StringType(), True),
        StructField("calledIpInfo_qosStatistics ", StringType(), True),
        StructField("OriginatingOperator ", StringType(), True),
        StructField("TerminatingOperator", StringType(), True),
    ]
)
